![alt text](./images/ML_01.jpg)

![alt text](./images/ML_02.jpg)

![alt text](./images/ML_03.jpg)

![alt text](./images/ML_04.jpg)

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# read image data 
s='./data/' 
num = 100
row = 240
col = 240
images = np.zeros((num, row, col))

# write your code here

n = 0
for i in range(0,10):
    for j in range(1, 11):
        images[n, :, :]=cv2.imread(s+str(i)+'/'+str(i)+'-'+str(j)+'.bmp',0 ) # 0 = read grayimg
        n = n+1

print(images.shape)  

(100, 240, 240)


In [7]:
# extract each image as feature vector
# use 6*6 grid to represent each origin image

feature = np.zeros((num, round(row/40), round(col/40)))
for num_i in range(0, num):
    for num_row in range(0, row):
        for num_col in range(0, col):
            if images[num_i, num_row, num_col] == 0: # 0 = black 
                feature[num_i, int(num_row/40), int(num_col/40)] += 1

dataset = feature[:,:].reshape(-1, round(row/40)*round(col/40)).astype(np.float32)
labels = np.asarray([int(i/10) for i in range(0,100)])

# write your code here

# print(feature)
print(feature.shape)
print(dataset.shape)
print(labels.shape)
print(labels)




(100, 6, 6)
(100, 36)
(100,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7
 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9]


In [17]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

# split data into training data and testing data
# write your code here

X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.4)


print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

print(y_train)

(60, 36)
(60,)
(40, 36)
(40,)
[4 3 5 9 8 5 0 6 5 5 2 7 1 9 1 6 1 2 8 4 6 0 3 1 9 4 9 9 3 3 5 6 2 3 0 2 9
 1 9 2 4 4 3 2 5 7 4 3 9 7 7 9 1 5 4 4 2 6 7 3]


In [4]:
# build model and evaluate your result

# write your code here


number of correct sample: 14
accuracy: 0.7
confusion matrix: [[2 0 0 0 0 0 0 0]
 [0 2 0 0 1 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 1 0 0 1 0]
 [0 0 0 2 2 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 1 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1]]
