![alt text](./images/ML_01.jpg)

![alt text](./images/ML_02.jpg)

![alt text](./images/ML_03.jpg)

![alt text](./images/ML_04.jpg)

In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# read image data 
s='./data/'  
num=100 #number of sample
row=240 #number of row
col=240 #number of column
images = np.zeros((num,row,col)) 

n=0 
for i in range(0,10):
    for j in range(1,11):
        images[n,:,:]=cv2.imread(s+str(i)+'/'+str(i)+'-'+str(j)+'.bmp',0)
        n=n+1

print(images.shape)  

(100, 240, 240)


In [7]:
# extract each image as feature vector
# use 6*6 grid to represent origin image

feature = np.zeros((num,round(row/40),round(col/40))) 
for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if images[ni,nr,nc]==0:
                feature[ni,int(nr/40),int(nc/40)]+=1

dataset = feature[:,:].reshape(-1,round(row/40)*round(col/40)).astype(np.float32) 
labels = np.asarray([int(i/10)  for i in range(0,100)])

print(dataset.shape)
print(labels.shape)
print(labels)

(100, 36)
(100,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7
 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9]


In [8]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

# split data into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.4)

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

print(y_train)

(60, 36)
(60,)
(40, 36)
(40,)
[1 5 1 6 8 6 6 0 5 1 4 7 9 5 5 3 8 4 3 8 2 6 8 5 6 4 7 1 9 2 2 5 4 1 0 6 9
 9 3 9 1 9 0 0 3 9 5 7 3 1 1 6 0 2 2 0 7 8 7 7]


In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = neighbors.KNeighborsClassifier(n_neighbors=10)
model.fit(X_train, y_train)


X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print(y_test)
print(y_pred)
print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: {}'.format(con_matrix))

[3 4 8 0 1 3 2 4 6 2 5 6 4 3 3 9 8 8 0 9 1 8 2 9 7 8 2 7 4 4 7 6 2 5 5 0 4
 3 0 7]
[6 4 8 0 1 5 2 4 6 7 5 6 4 5 5 9 5 8 1 9 1 8 7 7 7 8 2 7 1 4 7 6 1 5 5 0 4
 5 0 7]
number of correct sample: 28
accuracy: 0.7
confusion matrix: [[3 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 1 2 0 0 0 0 2 0 0]
 [0 0 0 0 0 4 1 0 0 0]
 [0 1 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 1 0 0 4 0]
 [0 0 0 0 0 0 0 1 0 2]]
