# Data Preprocessing Tools

In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset 

In [113]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [114]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [115]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data 

In [116]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [117]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

## 方法一

透過 column Transformer 挑選想要轉換的欄位

In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


print(X)

'''
在機器學習的世界中，都會先將資料轉換成 np.array 的形式，這是因為 np.array 的運算速度較快，
但dataframe的操作性較高，可以使用pandas的功能來進行資料處理，一般都是利用 dataframe 做資料清整，等到機器學習的時候再轉成 np.array

'''

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


'\n在機器學習的世界中，都會先將資料轉換成 np.array 的形式，這是因為 np.array 的運算速度較快，\n但dataframe的操作性較高，可以使用pandas的功能來進行資料處理，一般都是利用 dataframe 做資料清整，等到機器學習的時候再轉成 np.array\n\n'

In [119]:
## 注意: 抓特徵欄位資訊會跑掉
ct.get_feature_names_out()

array(['encoder__x0_France', 'encoder__x0_Germany', 'encoder__x0_Spain',
       'remainder__x1', 'remainder__x2'], dtype=object)

## 方法二

In [120]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [121]:
from sklearn.preprocessing import OneHotEncoder

# Select the column to encode
df = pd.read_csv('Data.csv')
column_to_encode = df[['Country']]

# Creating an instance of OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fitting the encoder to the column
encoder.fit(column_to_encode)

# Transforming the data to one-hot encoded format
encoded_data = encoder.transform(column_to_encode)

# Create a DataFrame from the encoded data and assign column names
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['Country']))


# Combine the original DataFrame with the new one-hot encoded DataFrame
result_df = pd.concat([encoded_df, df.drop('Country', axis=1)], axis=1)

print("Combined DataFrame with One-hot encoded data:")
print(result_df)

Combined DataFrame with One-hot encoded data:
   Country_France  Country_Germany  Country_Spain   Age   Salary Purchased
0             1.0              0.0            0.0  44.0  72000.0        No
1             0.0              0.0            1.0  27.0  48000.0       Yes
2             0.0              1.0            0.0  30.0  54000.0        No
3             0.0              0.0            1.0  38.0  61000.0        No
4             0.0              1.0            0.0  40.0      NaN       Yes
5             1.0              0.0            0.0  35.0  58000.0       Yes
6             0.0              0.0            1.0   NaN  52000.0        No
7             1.0              0.0            0.0  48.0  79000.0       Yes
8             0.0              1.0            0.0  50.0  83000.0        No
9             1.0              0.0            0.0  37.0  67000.0       Yes


### Encoding the Dependent Variable

In [122]:
from sklearn.preprocessing import LabelEncoder

# yes -> 1, no -> 0

le = LabelEncoder()
y = le.fit_transform(y)

In [123]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [124]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [125]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [126]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [127]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [128]:
print(y_test)

[0 1]


## Feature Scaling

## 標準化 => 平均值 = 0, 標準差 = 1

### 特徵標準化（Feature Standardization）是機器學習預處理中的一個重要步驟，主要目的有以下幾點：

- 提高學習算法的效率：許多機器學習算法，如梯度下降，其性能在特徵尺度相同的情況下會更好。當所有特徵都有相似的尺度時，梯度下降等算法在尋找最優解的過程中會更快收斂。

- 提升模型的表現：特徵標準化有助於消除數據中的偏差，使模型對於不同尺度的特徵沒有偏好，從而避免某些特徵在模型訓練過程中過度影響結果。

- 符合算法需求：一些算法，如支持向量機（SVM）和主成分分析（PCA），在處理數據時要求數據具有相同的尺度。特徵標準化確保了這些算法可以正常且有效地工作。

- 提高數據的數值穩定性：特徵標準化有助於避免在計算過程中出現數值計算問題，比如浮點數溢出或下溢。

- 提升模型的一般化能力：當數據經過標準化處理後，模型對於未見數據的泛化能力往往會更強，因為模型學習到的是特徵的相對重要性而非其數值大小。

In [129]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [130]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [131]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
